### ISSUE TITLE
Activating extension 'pflannery.vscode-versionlens' failed: Cannot find module 'systemjs'.

### ISSUE THREAD

**Issue by leolcao** [vscode-contrib/vscode-versionlens#97]
After upgrade VScode to 1.21.0, versionlens cann't working now, toggle developer tools to get this error message

**Comment by pflannery** [comment]
duplicate of https://github.com/vscode-contrib/vscode-versionlens/issues/91#issuecomment-360301349
