### ISSUE TITLE
Cannot find module 'systemjs' : windows 10 + vs code 1.19.2

### ISSUE THREAD

**Issue by tdurand** [vscode-contrib/vscode-versionlens#91]
Hi, 

I'm not able to make this plugin work on windows 10 + vs code 1.19.2

Here is a screenshot of devtools log:

![versionlens](https://user-images.githubusercontent.com/533590/35244325-8bab3df4-ff9e-11e7-9325-4e532435a470.jpg)

Will post a fix if I find it.

Thanks

**Comment by tdurand** [comment]
Reinstalling did work, this is weird because I had already tried before posting this bug... Anyway 😏 ! Thanks for your work, great plugin !

**Comment by andreasmarkussen** [comment]
@pflannery  - I just uninstalled and installed via the menu system, and then it worked, but it could be due to the fact, i do not have other modules that use 'systemjs'
